//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PersonMgr.rc
//
#define IDC_MORE                        3
#define IDD_ABOUTBOX                    100
#define IDC_TOOLBARTIMER                101
#define IDC_ALARMTIMER                  102
#define IDC_TIMER                       103
#define IDC_TIMERBUTTON                 104
#define IDR_MAINFRAME                   128
#define IDR_PERSONTYPE                  129
#define IDB_TREEVIEW                    130
#define IDD_QUERYDLG                    131
#define IDD_EDITDLG                     132
#define IDD_LOGINDLG                    133
#define IDB_LOGIN                       134
#define IDD_NMUSERDLG                   135
#define IDB_LOGIN1                      136
#define IDR_USERMENU                    138
#define IDD_ALARMDLG                    139
#define IDC_CURSOR1                     140
#define IDC_HAND                        140
#define IDD_DATEDLG                     141
#define IDD_TIMEDLG                     143
#define IDI_UP                          144
#define IDB_UP                          145
#define IDB_DOWN                        146
#define IDB_UP1                         147
#define IDB_DOWN1                       148
#define IDB_PLAY                        149
#define IDB_PAUSE                       150
#define IDB_STOP                        151
#define IDB_PLAY1                       152
#define IDB_STOP1                       153
#define IDD_SDSETUPDLG                  154
#define IDD_REGDLG                      156
#define IDI_TRAYICON                    157
#define IDB_CHINA                       158
#define IDR_IMAGE1                      159
#define IDB_BITMAP1                     162
#define IDB_CAPTION                     162
#define IDB_MAX                         163
#define IDB_PATTERN                     164
#define IDI_ICON1                       167
#define IDB_TRAY                        168
#define IDC_COMBO1                      1000
#define IDC_COLUMN1                     1001
#define IDC_COLUMNLIST                  1004
#define IDC_VALUELIST                   1005
#define IDC_EDIT                        1006
#define IDC_HELPINFO                    1008
#define IDC_COLUMNNAME                  1009
#define IDC_COLUMN2                     1010
#define IDC_COMBO2                      1011
#define IDC_PSDEDIT                     1011
#define IDC_COLUMN3                     1012
#define IDC_COMBO3                      1013
#define IDC_USERCOMBO                   1013
#define IDC_LOGINBMP                    1016
#define IDC_USERNAME                    1017
#define IDC_OLDPSDNAME                  1018
#define IDC_NEWPSDNAME                  1019
#define IDC_CFMPSDNAME                  1020
#define IDC_USERVALUE                   1021
#define IDC_OLDPSDVALUE                 1022
#define IDC_NEWPSDVALUE                 1023
#define IDC_CFMPSDVALUE                 1024
#define IDC_ALARMTYPE                   1024
#define IDC_NOTE                        1025
#define IDC_TIME                        1026
#define IDC_CALENDAR1                   1027
#define IDC_SETTIME                     1028
#define IDC_EDITHOUR                    1029
#define IDC_EDITMINUTE                  1030
#define IDC_EDITSECOND                  1031
#define IDC_UP                          1032
#define IDC_DOWN                        1033
#define IDC_PLAY                        1033
#define IDC_PAUSE                       1034
#define IDC_STOP                        1036
#define IDC_EDITTIME                    1036
#define IDC_COMBO_ONOFF                 1037
#define IDC_MACHINECODE                 1038
#define IDC_REGISTERCODE                1039
#define IDC_WEBSITE                     1041
#define IDC_VERSION                     1043
#define IDC_EXCUTE                      1044
#define IDC_S_USER                      1045
#define IDC_S_PASSWORD                  1046
#define IDC_S_DEFAULTPASSWORD           1047
#define IDC_S_AUTOONOFF                 1048
#define IDC_S_AUTOTIME                  1049
#define IDC_S_COLUMN                    1050
#define IDC_S_VALUE                     1051
#define IDC_S_HELPINFO                  1052
#define IDC_S_ALARMTIME                 1053
#define IDC_S_NOTE                      1054
#define IDC_INSERT                      32771
#define IDC_MODIFY                      32772
#define IDC_DELETE                      32773
#define IDC_REFRESH                     32774
#define IDC_LOGIN                       32777
#define IDC_ADDUSER                     32779
#define IDC_CHGPSD                      32780
#define IDC_EMAIL                       32781
#define IDC_BROWSE                      32782
#define IDC_SHUTDOWN                    32783
#define IDC_EMAIL1                      32783
#define IDC_CALCULATOR                  32784
#define IDC_GETEMAIL                    32785
#define IDC_COPYWEB                     32786
#define IDC_COPYEMAIL                   32787
#define IDC_DELETEUSER                  32788
#define IDC_SHUTDOWN_SETUP              32790
#define IDC_SETUP_AUTOSD                32791
#define IDC_REGISTER                    32792
#define IDC_REQUERY                     32793
#define IDC_CHINESE                     32796
#define IDC_ENGLISH                     32797
#define IDC_DYNAMIC                     32798
#define ID_INDICATOR_AUTO               59143
#define ID_INDICATOR_REGISTER           59144
#define IDS_SECTION1                    61447
#define IDS_ACCOUNT                     61447
#define IDS_SECTION2                    61448
#define IDS_PLAN                        61448
#define IDS_SECTION3                    61449
#define IDS_CONTACT                     61449
#define IDS_SECTION4                    61450
#define IDS_FAMILY                      61450
#define IDS_SECTION5                    61451
#define IDS_OTHER                       61451
#define IDS_BOOLHELPINFO                61452
#define IDS_BYTEHELPINFO                61453
#define IDS_SHORTHELPINFO               61454
#define IDS_LONGHELPINFO                61455
#define IDS_CURRENCYHELPINFO            61456
#define IDS_CALL                        61457
#define IDS_DOUBLEHELPINFO              61458
#define IDS_DATEHELPINFO                61459
#define IDS_TEXTHELPINFO                61460
#define IDS_QUERY_TYPE                  61461
#define IDS_UNDISP_CATALOG              61462
#define IDS_ACCOUNT_CATALOG             61463
#define IDS_PLAN_CATALOG                61464
#define IDS_CONTACT_CATALOG             61465
#define IDS_FAMILY_CATALOG              61466
#define IDS_OTHER_CATALOG               61467
#define IDS_ENABLEEMAIL                 61468
#define IDS_ENABLEWEB                   61469
#define IDS_SIMPLETIMETYPE              61470
#define IDS_SIMPLETIMEHELPINFO          61471
#define IDS_CALL_CATALOG                61472
#define IDS_SINGLEHELPINFO              62000
#define IDS_ROOT                        62001
#define IDS_VERSION                     62002

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        169
#define _APS_NEXT_COMMAND_VALUE         32799
#define _APS_NEXT_CONTROL_VALUE         1055
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
